[pytest]
testpaths =
    jd_parser/tests
    resume_parser/tests

python_files = test_*.py

norecursedirs =
    backups
    .git
    .pytest_cache
    __pycache__
    venv
    .venv
    _Resume Parser_Legacy
    Resume Parser

addopts = -ra
