"""expand_audit_log_schema

Revision ID: 38138ae6fa73
Revises: 449874d5dea4
Create Date: 2026-07-26 00:23:12.160065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38138ae6fa73'
down_revision: Union[str, Sequence[str], None] = '449874d5dea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.add_column('audit_logs', sa.Column('organization_id', sa.String(length=36), nullable=True))
    op.add_column('audit_logs', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('role_name', sa.String(length=150), nullable=True))
    op.add_column('audit_logs', sa.Column('session_id', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('request_id', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('correlation_id', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('trace_id', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('event_type', sa.String(length=120), nullable=False))
    op.add_column('audit_logs', sa.Column('resource_type', sa.String(length=150), nullable=True))
    op.add_column('audit_logs', sa.Column('resource_id', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('resource_name', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('endpoint', sa.String(length=500), nullable=True))
    op.add_column('audit_logs', sa.Column('http_method', sa.String(length=20), nullable=True))
    op.add_column('audit_logs', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('audit_logs', sa.Column('status_code', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('before_data', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('after_data', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('metadata', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('client_ip', sa.String(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('forwarded_ip', sa.String(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('device', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('browser', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('platform', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('country', sa.String(length=150), nullable=True))
    op.add_column('audit_logs', sa.Column('city', sa.String(length=150), nullable=True))
    op.add_column('audit_logs', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('audit_logs', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('audit_logs', sa.Column('request_body', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('query_params', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('headers', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('response_time_ms', sa.Float(), nullable=True))
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('audit_logs', 'module',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               nullable=True)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.drop_column('audit_logs', 'details')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('details', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.alter_column('audit_logs', 'module',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('audit_logs', 'response_time_ms')
    op.drop_column('audit_logs', 'headers')
    op.drop_column('audit_logs', 'query_params')
    op.drop_column('audit_logs', 'request_body')
    op.drop_column('audit_logs', 'longitude')
    op.drop_column('audit_logs', 'latitude')
    op.drop_column('audit_logs', 'city')
    op.drop_column('audit_logs', 'country')
    op.drop_column('audit_logs', 'platform')
    op.drop_column('audit_logs', 'browser')
    op.drop_column('audit_logs', 'device')
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'forwarded_ip')
    op.drop_column('audit_logs', 'client_ip')
    op.drop_column('audit_logs', 'metadata')
    op.drop_column('audit_logs', 'after_data')
    op.drop_column('audit_logs', 'before_data')
    op.drop_column('audit_logs', 'reason')
    op.drop_column('audit_logs', 'message')
    op.drop_column('audit_logs', 'status_code')
    op.drop_column('audit_logs', 'status')
    op.drop_column('audit_logs', 'http_method')
    op.drop_column('audit_logs', 'endpoint')
    op.drop_column('audit_logs', 'resource_name')
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'resource_type')
    op.drop_column('audit_logs', 'event_type')
    op.drop_column('audit_logs', 'trace_id')
    op.drop_column('audit_logs', 'correlation_id')
    op.drop_column('audit_logs', 'request_id')
    op.drop_column('audit_logs', 'session_id')
    op.drop_column('audit_logs', 'role_name')
    op.drop_column('audit_logs', 'email')
    op.drop_column('audit_logs', 'username')
    op.drop_column('audit_logs', 'organization_id')
    op.drop_column('audit_logs', 'tenant_id')
    # ### end Alembic commands ###
