"""Initial database schema

Revision ID: 65cb880e2ac7
Revises: 
Create Date: 2026-07-21 11:12:56.528479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65cb880e2ac7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('candidate_certifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('certification_name', sa.String(length=255), nullable=False),
    sa.Column('issuing_organization', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_certifications_candidate_id'), 'candidate_certifications', ['candidate_id'], unique=False)
    op.create_table('candidate_education',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('passing_year', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_education_candidate_id'), 'candidate_education', ['candidate_id'], unique=False)
    op.create_table('candidate_experience',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('experience_years', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_experience_candidate_id'), 'candidate_experience', ['candidate_id'], unique=False)
    op.create_table('candidate_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('technologies', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_projects_candidate_id'), 'candidate_projects', ['candidate_id'], unique=False)
    op.create_table('candidate_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('skill_name', sa.String(length=150), nullable=False),
    sa.Column('skill_category', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_skills_candidate_id'), 'candidate_skills', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_skills_skill_name'), 'candidate_skills', ['skill_name'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_code', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('experience_years', sa.Float(), nullable=False),
    sa.Column('current_designation', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_candidate_code'), 'candidates', ['candidate_code'], unique=True)
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=False)
    op.create_index(op.f('ix_candidates_full_name'), 'candidates', ['full_name'], unique=False)
    op.create_table('job_descriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_code', sa.String(length=50), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('experience_required', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_code')
    )
    op.create_table('job_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('skill_name', sa.String(length=150), nullable=False),
    sa.Column('skill_category', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_skills_job_id'), 'job_skills', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_skills_skill_name'), 'job_skills', ['skill_name'], unique=False)
    op.create_table('match_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_results_candidate_id'), 'match_results', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_match_results_job_id'), 'match_results', ['job_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('organization_code', sa.String(length=50), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_code'),
    sa.UniqueConstraint('organization_name')
    )
    op.create_table('resumes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('resume_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_candidate_id'), 'resumes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_resumes_resume_hash'), 'resumes', ['resume_hash'], unique=True)
    op.create_table('search_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=False),
    sa.Column('search_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_resumes_resume_hash'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_candidate_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_match_results_job_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_candidate_id'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_index(op.f('ix_job_skills_skill_name'), table_name='job_skills')
    op.drop_index(op.f('ix_job_skills_job_id'), table_name='job_skills')
    op.drop_table('job_skills')
    op.drop_table('job_descriptions')
    op.drop_index(op.f('ix_candidates_full_name'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_candidate_code'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_candidate_skills_skill_name'), table_name='candidate_skills')
    op.drop_index(op.f('ix_candidate_skills_candidate_id'), table_name='candidate_skills')
    op.drop_table('candidate_skills')
    op.drop_index(op.f('ix_candidate_projects_candidate_id'), table_name='candidate_projects')
    op.drop_table('candidate_projects')
    op.drop_index(op.f('ix_candidate_experience_candidate_id'), table_name='candidate_experience')
    op.drop_table('candidate_experience')
    op.drop_index(op.f('ix_candidate_education_candidate_id'), table_name='candidate_education')
    op.drop_table('candidate_education')
    op.drop_index(op.f('ix_candidate_certifications_candidate_id'), table_name='candidate_certifications')
    op.drop_table('candidate_certifications')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
