import pytest

from jd_parser.extractors.skills_extractor import extract_skills


@pytest.mark.parametrize(
    "text,expected_technical,expected_functional,expected_soft",
    [
        ("Python", ["Python"], [], []),
        ("java", ["Java"], [], []),
        ("JavaScript", ["JavaScript"], [], []),
        ("Type Script", ["TypeScript"], [], []),
        ("C++", ["C++"], [], []),
        ("c sharp", ["C#"], [], []),
        ("Go", ["Go"], [], []),
        ("RUST", ["Rust"], [], []),
        ("php", ["PHP"], [], []),
        ("RubY", ["Ruby"], [], []),
        ("Kotlin", ["Kotlin"], [], []),
        ("Swift", ["Swift"], [], []),
        ("Scala", ["Scala"], [], []),
        ("R", ["R"], [], []),
        ("MATLAB", ["MATLAB"], [], []),
        ("HTML", ["HTML"], [], []),
        ("css", ["CSS"], [], []),
        ("React", ["React"], [], []),
        ("angular", ["Angular"], [], []),
        ("Vue", ["Vue"], [], []),
        ("Node.js", ["Node.js"], [], []),
        ("Express", ["Express"], [], []),
        ("Django", ["Django"], [], []),
        ("flask", ["Flask"], [], []),
        ("FastAPI", ["FastAPI"], [], []),
        ("spring boot", ["Spring Boot"], [], []),
        ("asp.net", ["ASP.NET"], [], []),
        ("MySQL", ["MySQL"], [], []),
        ("postgresql", ["PostgreSQL"], [], []),
        ("SQL Server", ["SQL Server"], [], []),
        ("oracle", ["Oracle"], [], []),
        ("MongoDB", ["MongoDB"], [], []),
        ("redis", ["Redis"], [], []),
        ("Sqlite", ["SQLite"], [], []),
        ("Cassandra", ["Cassandra"], [], []),
        ("Elasticsearch", ["Elasticsearch"], [], []),
        ("aws", ["AWS"], [], []),
        ("Azure", ["Azure"], [], []),
        ("Google Cloud", ["Google Cloud"], [], []),
        ("GCP", ["GCP"], [], []),
        ("OCI", ["OCI"], [], []),
        ("OpenStack", ["OpenStack"], [], []),
        ("Docker", ["Docker"], [], []),
        ("Kubernetes", ["Kubernetes"], [], []),
        ("Terraform", ["Terraform"], [], []),
        ("Ansible", ["Ansible"], [], []),
        ("Jenkins", ["Jenkins"], [], []),
        ("GitHub Actions", ["GitHub Actions"], [], []),
        ("GitLab CI", ["GitLab CI"], [], []),
        ("TCP/IP", ["TCP/IP"], [], []),
        ("BGP", ["BGP"], [], []),
        ("OSPF", ["OSPF"], [], []),
        ("MPLS", ["MPLS"], [], []),
        ("VPN", ["VPN"], [], []),
        ("LAN", ["LAN"], [], []),
        ("WAN", ["WAN"], [], []),
        ("Routing", ["Routing"], [], []),
        ("Switching", ["Switching"], [], []),
        ("5G", ["5G"], [], []),
        ("4G LTE", ["4G LTE"], [], []),
        ("VoLTE", ["VoLTE"], [], []),
        ("IMS", ["IMS"], [], []),
        ("GPON", ["GPON"], [], []),
        ("DWDM", ["DWDM"], [], []),
        ("SDH", ["SDH"], [], []),
        ("OTN", ["OTN"], [], []),
        ("MPLS-TP", ["MPLS-TP"], [], []),
        ("Cisco", ["Cisco"], [], []),
        ("Juniper", ["Juniper"], [], []),
        ("Nokia", ["Nokia"], [], []),
        ("Huawei", ["Huawei"], [], []),
        ("Ericsson", ["Ericsson"], [], []),
        ("Ciena", ["Ciena"], [], []),
        ("Tejas", ["Tejas"], [], []),
        ("Firewall", ["Firewall"], [], []),
        ("Fortinet", ["Fortinet"], [], []),
        ("Palo Alto", ["Palo Alto"], [], []),
        ("CrowdStrike", ["CrowdStrike"], [], []),
        ("SIEM", ["SIEM"], [], []),
        ("SOC", ["SOC"], [], []),
        ("EDR", ["EDR"], [], []),
        ("XDR", ["XDR"], [], []),
        ("Machine Learning", ["Machine Learning"], [], []),
        ("Deep Learning", ["Deep Learning"], [], []),
        ("NLP", ["NLP"], [], []),
        ("LLM", ["LLM"], [], []),
        ("TensorFlow", ["TensorFlow"], [], []),
        ("PyTorch", ["PyTorch"], [], []),
        ("Scikit-learn", ["Scikit-learn"], [], []),
        ("OpenAI API", ["OpenAI API"], [], []),
        ("SAP", ["SAP"], [], []),
        ("Oracle ERP", ["Oracle ERP"], [], []),
        ("Salesforce", ["Salesforce"], [], []),
        ("Workday", ["Workday"], [], []),
        ("ServiceNow", ["ServiceNow"], [], []),
        (
            "Python, Java, JavaScript, TypeScript, C, C++, C#",
            ["Python", "Java", "JavaScript", "TypeScript", "C", "C++", "C#"],
            [],
            [],
        ),
        (
            "AWS Azure Google Cloud GCP OCI OpenStack",
            ["AWS", "Azure", "Google Cloud", "GCP", "OCI", "OpenStack"],
            [],
            [],
        ),
        (
            "Docker Kubernetes Terraform Ansible Jenkins GitHub Actions GitLab CI",
            ["Docker", "Kubernetes", "Terraform", "Ansible", "Jenkins", "GitHub Actions", "GitLab CI"],
            [],
            [],
        ),
        (
            "HTML CSS React Angular Vue Node.js Express Django Flask FastAPI Spring Boot ASP.NET",
            ["HTML", "CSS", "React", "Angular", "Vue", "Node.js", "Express", "Django", "Flask", "FastAPI", "Spring Boot", "ASP.NET"],
            [],
            [],
        ),
        (
            "MySQL PostgreSQL SQL Server Oracle MongoDB Redis SQLite Cassandra Elasticsearch",
            ["MySQL", "PostgreSQL", "SQL Server", "Oracle", "MongoDB", "Redis", "SQLite", "Cassandra", "Elasticsearch"],
            [],
            [],
        ),
        (
            "5G 4G LTE VoLTE IMS GPON DWDM SDH OTN MPLS-TP Cisco Juniper Nokia Huawei Ericsson Ciena Tejas",
            ["5G", "4G LTE", "VoLTE", "IMS", "GPON", "DWDM", "SDH", "OTN", "MPLS-TP", "Cisco", "Juniper", "Nokia", "Huawei", "Ericsson", "Ciena", "Tejas"],
            [],
            [],
        ),
        (
            "Machine Learning Deep Learning NLP LLM TensorFlow PyTorch Scikit-learn OpenAI API",
            ["Machine Learning", "Deep Learning", "NLP", "LLM", "TensorFlow", "PyTorch", "Scikit-learn", "OpenAI API"],
            [],
            [],
        ),
        (
            "SAP Oracle ERP Salesforce Workday ServiceNow",
            ["SAP", "Oracle ERP", "Salesforce", "Workday", "ServiceNow"],
            [],
            [],
        ),
        (
            "aws, Azure, gcp, Google Cloud, azure",
            ["AWS", "Azure", "GCP", "Google Cloud"],
            [],
            [],
        ),
        (
            "python python python",
            ["Python"],
            [],
            [],
        ),
        (
            "C# and C++ developer",
            ["C#", "C++"],
            [],
            [],
        ),
        (
            "node js and express framework",
            ["Node.js", "Express"],
            [],
            [],
        ),
        (
            "springboot and asp net",
            ["Spring Boot", "ASP.NET"],
            [],
            [],
        ),
        (
            "postgres and mysql",
            ["PostgreSQL", "MySQL"],
            [],
            [],
        ),
        (
            "oracle database and mongo db",
            ["Oracle", "MongoDB"],
            [],
            [],
        ),
        (
            "aws cloud solutions and azure services",
            ["AWS", "Azure"],
            [],
            [],
        ),
        (
            "docker containers and k8s",
            ["Docker", "Kubernetes"],
            [],
            [],
        ),
        (
            "terraform ansible jenkins github actions",
            ["Terraform", "Ansible", "Jenkins", "GitHub Actions"],
            [],
            [],
        ),
        (
            "bgp ospf and mpls",
            ["BGP", "OSPF", "MPLS"],
            [],
            [],
        ),
        (
            "5g lte and volte",
            ["5G", "4G LTE", "VoLTE"],
            [],
            [],
        ),
        (
            "palo alto firewall and fortinet",
            ["Palo Alto", "Firewall", "Fortinet"],
            [],
            [],
        ),
        (
            "tensorflow and pytorch",
            ["TensorFlow", "PyTorch"],
            [],
            [],
        ),
        (
            "service now and sales force",
            ["ServiceNow", "Salesforce"],
            [],
            [],
        ),
        ("This text has no skills.", [], [], []),
    ],
)
def test_extract_skills(text, expected_technical, expected_functional, expected_soft):
    result = extract_skills(text)
    assert result["technical_skills"] == expected_technical
    assert result["functional_skills"] == expected_functional
    assert result["soft_skills"] == expected_soft


def test_extract_skills_return_structure_for_none_text():
    result = extract_skills(None)
    assert result == {"technical_skills": [], "functional_skills": [], "soft_skills": []}


def test_extract_skills_preserves_order_and_uniqueness():
    result = extract_skills("Python, Java, python, JAVA, C# and c#")
    assert result["technical_skills"] == ["Python", "Java", "C#"]
    assert result["functional_skills"] == []
    assert result["soft_skills"] == []
